spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}a85880dca4ffe40def520bf7af250d3b7af9bbaead00472a7748099bbe442f59'

token:
  expiration_time: 864000000
  secret: mytoken-default

gateway:
  ip: 127.0.0.1
  
order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders